import Head from 'next/head'
import Section from '@/components/UI/section/Section'
import Header from '../components/Header'
import Footer from '../components/Footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        
      </Head>

      <main className='flex  h-max-[4000px] h-[720px] w-full flex-col '>
        
        <div className='flex   justify-between items-center flex-col h-full gap-6 sm:px-4 px-2 '>
        <Header />
          <Section />
          <Footer />
        </div>
       



      </main>
    </>
  )
}
